// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brands.sql

package repository

import (
	"context"
)

const getBrandByID = `-- name: GetBrandByID :one
SELECT id, name, tier, k_brand, is_active, models, created_at
FROM brands
WHERE id = $1
`

// 根据 ID 查询品牌
func (q *Queries) GetBrandByID(ctx context.Context, id int32) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tier,
		&i.KBrand,
		&i.IsActive,
		&i.Models,
		&i.CreatedAt,
	)
	return i, err
}

const getBrandByName = `-- name: GetBrandByName :one
SELECT id, name, tier, k_brand, is_active, models, created_at
FROM brands
WHERE name = $1
`

// 根据品牌名查询品牌
func (q *Queries) GetBrandByName(ctx context.Context, name string) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByName, name)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tier,
		&i.KBrand,
		&i.IsActive,
		&i.Models,
		&i.CreatedAt,
	)
	return i, err
}

const listBrands = `-- name: ListBrands :many

SELECT id, name, tier, k_brand, is_active, models, created_at
FROM brands
WHERE is_active = TRUE
ORDER BY k_brand DESC, name ASC
`

// queries/brands.sql
// 品牌表数据访问查询
// 查询所有激活的品牌，按档次与名称排序
func (q *Queries) ListBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.Query(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tier,
			&i.KBrand,
			&i.IsActive,
			&i.Models,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
