// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coefficient_configs.sql

package repository

import (
	"context"
)

const getCoefficientByKey = `-- name: GetCoefficientByKey :one
SELECT id, key, value, description, updated_at
FROM coefficient_configs
WHERE key = $1
`

// 根据配置键查询系数
func (q *Queries) GetCoefficientByKey(ctx context.Context, key string) (CoefficientConfig, error) {
	row := q.db.QueryRow(ctx, getCoefficientByKey, key)
	var i CoefficientConfig
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const listCoefficientConfigs = `-- name: ListCoefficientConfigs :many

SELECT id, key, value, description, updated_at
FROM coefficient_configs
ORDER BY key ASC
`

// queries/coefficient_configs.sql
// 系数配置表数据访问查询
// 查询所有系数配置
func (q *Queries) ListCoefficientConfigs(ctx context.Context) ([]CoefficientConfig, error) {
	rows, err := q.db.Query(ctx, listCoefficientConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoefficientConfig
	for rows.Next() {
		var i CoefficientConfig
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoefficientValue = `-- name: UpdateCoefficientValue :one
UPDATE coefficient_configs
SET value = $2, updated_at = NOW()
WHERE key = $1
RETURNING id, key, value, description, updated_at
`

type UpdateCoefficientValueParams struct {
	Key   string
	Value float64
}

// 更新某个系数的值，返回更新后的记录
func (q *Queries) UpdateCoefficientValue(ctx context.Context, arg UpdateCoefficientValueParams) (CoefficientConfig, error) {
	row := q.db.QueryRow(ctx, updateCoefficientValue, arg.Key, arg.Value)
	var i CoefficientConfig
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}
