// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evaluations.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEvaluations = `-- name: CountEvaluations :one
SELECT COUNT(*) AS total
FROM evaluations
WHERE ($1::TEXT IS NULL OR forklift_type = $1)
`

// 统计评估记录总数（用于分页）
func (q *Queries) CountEvaluations(ctx context.Context, forkliftType pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countEvaluations, forkliftType)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createEvaluation = `-- name: CreateEvaluation :one

INSERT INTO evaluations (
    forklift_type, brand, model, original_price, purchase_year, sale_year,
    usage_hours, work_condition, fuel_type, can_drive, hydraulic_ok,
    k_time, k_hours, k_work, k_brand, k_condition, k_market,
    estimated_value, confidence_low, confidence_high, report_pdf_path
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21
)
RETURNING id, created_at, updated_at
`

type CreateEvaluationParams struct {
	ForkliftType   string
	Brand          string
	Model          pgtype.Text
	OriginalPrice  float64
	PurchaseYear   int32
	SaleYear       int32
	UsageHours     int32
	WorkCondition  string
	FuelType       pgtype.Text
	CanDrive       bool
	HydraulicOk    bool
	KTime          float64
	KHours         float64
	KWork          float64
	KBrand         float64
	KCondition     float64
	KMarket        float64
	EstimatedValue float64
	ConfidenceLow  float64
	ConfidenceHigh float64
	ReportPdfPath  pgtype.Text
}

type CreateEvaluationRow struct {
	ID        int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

// queries/evaluations.sql
// 评估记录与部件状态表数据访问查询
// 创建评估记录主表，返回新生成的 ID
func (q *Queries) CreateEvaluation(ctx context.Context, arg CreateEvaluationParams) (CreateEvaluationRow, error) {
	row := q.db.QueryRow(ctx, createEvaluation,
		arg.ForkliftType,
		arg.Brand,
		arg.Model,
		arg.OriginalPrice,
		arg.PurchaseYear,
		arg.SaleYear,
		arg.UsageHours,
		arg.WorkCondition,
		arg.FuelType,
		arg.CanDrive,
		arg.HydraulicOk,
		arg.KTime,
		arg.KHours,
		arg.KWork,
		arg.KBrand,
		arg.KCondition,
		arg.KMarket,
		arg.EstimatedValue,
		arg.ConfidenceLow,
		arg.ConfidenceHigh,
		arg.ReportPdfPath,
	)
	var i CreateEvaluationRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const createEvaluationItem = `-- name: CreateEvaluationItem :one
INSERT INTO evaluation_items (
    evaluation_id, category_code, category_name, item_code, item_name,
    status, category_weight, item_weight, score
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
RETURNING id
`

type CreateEvaluationItemParams struct {
	EvaluationID   int64
	CategoryCode   string
	CategoryName   string
	ItemCode       string
	ItemName       string
	Status         string
	CategoryWeight float64
	ItemWeight     float64
	Score          float64
}

// 创建单条部件状态记录
func (q *Queries) CreateEvaluationItem(ctx context.Context, arg CreateEvaluationItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, createEvaluationItem,
		arg.EvaluationID,
		arg.CategoryCode,
		arg.CategoryName,
		arg.ItemCode,
		arg.ItemName,
		arg.Status,
		arg.CategoryWeight,
		arg.ItemWeight,
		arg.Score,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getEvaluation = `-- name: GetEvaluation :one
SELECT id, forklift_type, brand, model, original_price, purchase_year, sale_year,
       usage_hours, work_condition, fuel_type, can_drive, hydraulic_ok,
       k_time, k_hours, k_work, k_brand, k_condition, k_market,
       estimated_value, confidence_low, confidence_high, report_pdf_path,
       created_at, updated_at
FROM evaluations
WHERE id = $1
`

// 根据 ID 查询评估记录主表
func (q *Queries) GetEvaluation(ctx context.Context, id int64) (Evaluation, error) {
	row := q.db.QueryRow(ctx, getEvaluation, id)
	var i Evaluation
	err := row.Scan(
		&i.ID,
		&i.ForkliftType,
		&i.Brand,
		&i.Model,
		&i.OriginalPrice,
		&i.PurchaseYear,
		&i.SaleYear,
		&i.UsageHours,
		&i.WorkCondition,
		&i.FuelType,
		&i.CanDrive,
		&i.HydraulicOk,
		&i.KTime,
		&i.KHours,
		&i.KWork,
		&i.KBrand,
		&i.KCondition,
		&i.KMarket,
		&i.EstimatedValue,
		&i.ConfidenceLow,
		&i.ConfidenceHigh,
		&i.ReportPdfPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvaluationItems = `-- name: ListEvaluationItems :many
SELECT id, evaluation_id, category_code, category_name, item_code, item_name,
       status, category_weight, item_weight, score
FROM evaluation_items
WHERE evaluation_id = $1
ORDER BY id ASC
`

// 根据评估 ID 查询所有部件状态
func (q *Queries) ListEvaluationItems(ctx context.Context, evaluationID int64) ([]EvaluationItem, error) {
	rows, err := q.db.Query(ctx, listEvaluationItems, evaluationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvaluationItem
	for rows.Next() {
		var i EvaluationItem
		if err := rows.Scan(
			&i.ID,
			&i.EvaluationID,
			&i.CategoryCode,
			&i.CategoryName,
			&i.ItemCode,
			&i.ItemName,
			&i.Status,
			&i.CategoryWeight,
			&i.ItemWeight,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvaluations = `-- name: ListEvaluations :many
SELECT id, forklift_type, brand, model, original_price, purchase_year, sale_year,
       usage_hours, work_condition, fuel_type, can_drive, hydraulic_ok,
       k_time, k_hours, k_work, k_brand, k_condition, k_market,
       estimated_value, confidence_low, confidence_high, report_pdf_path,
       created_at, updated_at
FROM evaluations
WHERE ($3::TEXT IS NULL OR forklift_type = $3)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListEvaluationsParams struct {
	Limit        int32
	Offset       int32
	ForkliftType pgtype.Text
}

// 分页查询评估历史列表（可选按类型筛选）
func (q *Queries) ListEvaluations(ctx context.Context, arg ListEvaluationsParams) ([]Evaluation, error) {
	rows, err := q.db.Query(ctx, listEvaluations, arg.Limit, arg.Offset, arg.ForkliftType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evaluation
	for rows.Next() {
		var i Evaluation
		if err := rows.Scan(
			&i.ID,
			&i.ForkliftType,
			&i.Brand,
			&i.Model,
			&i.OriginalPrice,
			&i.PurchaseYear,
			&i.SaleYear,
			&i.UsageHours,
			&i.WorkCondition,
			&i.FuelType,
			&i.CanDrive,
			&i.HydraulicOk,
			&i.KTime,
			&i.KHours,
			&i.KWork,
			&i.KBrand,
			&i.KCondition,
			&i.KMarket,
			&i.EstimatedValue,
			&i.ConfidenceLow,
			&i.ConfidenceHigh,
			&i.ReportPdfPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvaluationReportPath = `-- name: UpdateEvaluationReportPath :one
UPDATE evaluations
SET report_pdf_path = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, report_pdf_path, updated_at
`

type UpdateEvaluationReportPathParams struct {
	ID            int64
	ReportPdfPath pgtype.Text
}

type UpdateEvaluationReportPathRow struct {
	ID            int64
	ReportPdfPath pgtype.Text
	UpdatedAt     pgtype.Timestamp
}

// 更新评估记录的 PDF 报告路径
func (q *Queries) UpdateEvaluationReportPath(ctx context.Context, arg UpdateEvaluationReportPathParams) (UpdateEvaluationReportPathRow, error) {
	row := q.db.QueryRow(ctx, updateEvaluationReportPath, arg.ID, arg.ReportPdfPath)
	var i UpdateEvaluationReportPathRow
	err := row.Scan(&i.ID, &i.ReportPdfPath, &i.UpdatedAt)
	return i, err
}
