// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: historical_sales.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHistoricalSale = `-- name: CreateHistoricalSale :one

INSERT INTO historical_sales (
    forklift_type, brand, model, original_price, purchase_year, sale_year,
    usage_hours, work_condition, fuel_type, sale_price
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10
)
RETURNING id, imported_at
`

type CreateHistoricalSaleParams struct {
	ForkliftType  string
	Brand         string
	Model         pgtype.Text
	OriginalPrice float64
	PurchaseYear  int32
	SaleYear      int32
	UsageHours    int32
	WorkCondition string
	FuelType      pgtype.Text
	SalePrice     float64
}

type CreateHistoricalSaleRow struct {
	ID         int64
	ImportedAt pgtype.Timestamp
}

// queries/historical_sales.sql
// 历史成交数据表访问查询（用于算法离线校准）
// 插入一条历史成交记录
func (q *Queries) CreateHistoricalSale(ctx context.Context, arg CreateHistoricalSaleParams) (CreateHistoricalSaleRow, error) {
	row := q.db.QueryRow(ctx, createHistoricalSale,
		arg.ForkliftType,
		arg.Brand,
		arg.Model,
		arg.OriginalPrice,
		arg.PurchaseYear,
		arg.SaleYear,
		arg.UsageHours,
		arg.WorkCondition,
		arg.FuelType,
		arg.SalePrice,
	)
	var i CreateHistoricalSaleRow
	err := row.Scan(&i.ID, &i.ImportedAt)
	return i, err
}

const listHistoricalSales = `-- name: ListHistoricalSales :many
SELECT id, forklift_type, brand, model, original_price, purchase_year, sale_year,
       usage_hours, work_condition, fuel_type, sale_price, imported_at
FROM historical_sales
WHERE ($2::TEXT IS NULL OR forklift_type = $2)
  AND ($3::TEXT IS NULL OR brand = $3)
ORDER BY imported_at DESC
LIMIT $1
`

type ListHistoricalSalesParams struct {
	Limit        int32
	ForkliftType pgtype.Text
	Brand        pgtype.Text
}

// 按叉车类型与品牌查询历史成交数据
func (q *Queries) ListHistoricalSales(ctx context.Context, arg ListHistoricalSalesParams) ([]HistoricalSale, error) {
	rows, err := q.db.Query(ctx, listHistoricalSales, arg.Limit, arg.ForkliftType, arg.Brand)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoricalSale
	for rows.Next() {
		var i HistoricalSale
		if err := rows.Scan(
			&i.ID,
			&i.ForkliftType,
			&i.Brand,
			&i.Model,
			&i.OriginalPrice,
			&i.PurchaseYear,
			&i.SaleYear,
			&i.UsageHours,
			&i.WorkCondition,
			&i.FuelType,
			&i.SalePrice,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
