// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Brand struct {
	ID        int32
	Name      string
	Tier      string
	KBrand    float64
	IsActive  pgtype.Bool
	Models    []byte
	CreatedAt pgtype.Timestamp
}

type CoefficientConfig struct {
	ID          int32
	Key         string
	Value       float64
	Description pgtype.Text
	UpdatedAt   pgtype.Timestamp
}

type Evaluation struct {
	ID             int64
	ForkliftType   string
	Brand          string
	Model          pgtype.Text
	OriginalPrice  float64
	PurchaseYear   int32
	SaleYear       int32
	UsageHours     int32
	WorkCondition  string
	FuelType       pgtype.Text
	CanDrive       bool
	HydraulicOk    bool
	KTime          float64
	KHours         float64
	KWork          float64
	KBrand         float64
	KCondition     float64
	KMarket        float64
	EstimatedValue float64
	ConfidenceLow  float64
	ConfidenceHigh float64
	ReportPdfPath  pgtype.Text
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type EvaluationItem struct {
	ID             int64
	EvaluationID   int64
	CategoryCode   string
	CategoryName   string
	ItemCode       string
	ItemName       string
	Status         string
	CategoryWeight float64
	ItemWeight     float64
	Score          float64
}

type HistoricalSale struct {
	ID            int64
	ForkliftType  string
	Brand         string
	Model         pgtype.Text
	OriginalPrice float64
	PurchaseYear  int32
	SaleYear      int32
	UsageHours    int32
	WorkCondition string
	FuelType      pgtype.Text
	SalePrice     float64
	ImportedAt    pgtype.Timestamp
}

type PartConfig struct {
	ID             int32
	ForkliftType   string
	CategoryCode   string
	CategoryName   string
	CategoryWeight float64
	ItemCode       string
	ItemName       string
	ItemWeight     float64
}
