// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: part_configs.sql

package repository

import (
	"context"
)

const getPartConfigByItemCode = `-- name: GetPartConfigByItemCode :one
SELECT id, forklift_type, category_code, category_name, category_weight,
       item_code, item_name, item_weight
FROM part_configs
WHERE forklift_type = $1 AND item_code = $2
`

type GetPartConfigByItemCodeParams struct {
	ForkliftType string
	ItemCode     string
}

// 根据叉车类型和条目编码查询部件配置
func (q *Queries) GetPartConfigByItemCode(ctx context.Context, arg GetPartConfigByItemCodeParams) (PartConfig, error) {
	row := q.db.QueryRow(ctx, getPartConfigByItemCode, arg.ForkliftType, arg.ItemCode)
	var i PartConfig
	err := row.Scan(
		&i.ID,
		&i.ForkliftType,
		&i.CategoryCode,
		&i.CategoryName,
		&i.CategoryWeight,
		&i.ItemCode,
		&i.ItemName,
		&i.ItemWeight,
	)
	return i, err
}

const listPartConfigs = `-- name: ListPartConfigs :many

SELECT id, forklift_type, category_code, category_name, category_weight,
       item_code, item_name, item_weight
FROM part_configs
WHERE forklift_type = $1
ORDER BY id ASC
`

// queries/part_configs.sql
// 部件配置表数据访问查询
// 根据叉车类型查询所有部件配置，按类别与条目顺序排序
func (q *Queries) ListPartConfigs(ctx context.Context, forkliftType string) ([]PartConfig, error) {
	rows, err := q.db.Query(ctx, listPartConfigs, forkliftType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartConfig
	for rows.Next() {
		var i PartConfig
		if err := rows.Scan(
			&i.ID,
			&i.ForkliftType,
			&i.CategoryCode,
			&i.CategoryName,
			&i.CategoryWeight,
			&i.ItemCode,
			&i.ItemName,
			&i.ItemWeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
